### ISSUE TITLE
Modify MultiQC module results

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#87]
**Is your feature request related to a problem? Please describe.**
At the moment the MultiQC results are in reverse order, which doesn't make sense in the natural way of reading and doing quality control.

**Describe the solution you'd like**
Provide and/or modify the default multiqc.config file that comes with the singularity/docker/conda 'images' to reflect the 
order in which each module is run.

More context is provided here: https://multiqc.info/docs/#order-of-modules
 
**Describe alternatives you've considered**
Add to documentation to read in reverse

**Example**

I've not tested this, but something along the lines of?:

```yaml
report_comment: >
    This report has been generated by the <a href="https://github.com/nf-core/eager" target="_blank">nf-core/eager</a>
    analysis pipeline. For information about how to interpret these results, please see the
    <a href="https://github.com/nf-core/eager" target="_blank">documentation</a>.
report_section_order:
    nf-core/eager-software-versions:
        order: -1000
    fastqc:
        after: 'nf-core/eager-software-versions'
    adapterRemoval:
        after: 'fastqc'
    Samtools:
        after: 'adapterRemoval'
    dedup:
        after: 'Samtools'
    qualimap:
        after: 'dedup'
    preseq:
        after: 'qualimap'
```

If you agree I will try it out and then do a pull request.
